version: "2"

formatters:
  enable:
    - gofmt

linters:
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "S1034"
      - linters:
          - staticcheck
        text: "ST1023"
      - linters:
          - staticcheck
        text: "QF1003"
      - linters:
          - staticcheck
        text: "QF1011"
      - linters:
          - errcheck
        text: "."
