language: go

dist: jammy

go:
- 1.21.x
- 1.22.x
- 1.23.x

notifications:
  email: true

env:
  global:
    - GO111MODULE=on

before_install:
- sudo apt-get update
- eval "$(pyenv init -)"
- python -V
- >-
  [ -z "${TRAVIS_TAG}" ] &&  [ "${TRAVIS_PULL_REQUEST}" == "false" ]
  && openssl aes-256-cbc -K $encrypted_d4a185972ecc_key -iv $encrypted_d4a185972ecc_iv -in pdns.env.enc -out pdns.env -d || true
  && openssl aes-256-cbc -K $encrypted_6de0fb2f002f_key -iv $encrypted_6de0fb2f002f_iv -in directlink.env.enc -out directlink.env -d || true
  && openssl aes-256-cbc -K $encrypted_3d8a3eb98382_key -iv $encrypted_3d8a3eb98382_iv -in transit.env.enc -out transit.env -d || true
  && openssl aes-256-cbc -K $encrypted_fc092b9428d6_key -iv $encrypted_fc092b9428d6_iv -in cis.env.enc -out cis.env -d || true
  && openssl aes-256-cbc -K $encrypted_89a9eb4f9417_key -iv $encrypted_89a9eb4f9417_iv -in dns.env.enc -out dns.env -d || true
  && openssl aes-256-cbc -K $encrypted_fb1b85a9795b_key -iv $encrypted_fb1b85a9795b_iv -in cislog.env.enc -out cislog.env -d || true

install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.60.3

script:
  - make travis-ci

before_deploy:
  - nvm install 20
  - npm install npm@latest -g
  - npm install @semantic-release/changelog
  - npm install @semantic-release/exec
  - npm install @semantic-release/git
  - npm install @semantic-release/github
  - pip install bump2version

deploy:
  - provider: script
    script: npx semantic-release
    skip_cleanup: true
    on:
      go: '1.23.x'
      branch: master
